FROM golang:1.20-alpine AS builder

RUN apk update && apk add --no-cache git

RUN git clone https://github.com/enfein/mieru.git /build

WORKDIR /build

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mita cmd/mita/mita.go


FROM alpine AS base

COPY --from=builder /build/mita /usr/local/bin/

WORKDIR /app

COPY . .

RUN chmod +x ./start.sh && adduser -H -D -g "" mita && mkdir -p /etc/mita

CMD ["./start.sh"]