// Copyright (C) 2021  mieru authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: appctl/proto/clientcfg.proto

package appctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplexingLevel int32

const (
	MultiplexingLevel_MULTIPLEXING_DEFAULT MultiplexingLevel = 0
	MultiplexingLevel_MULTIPLEXING_OFF     MultiplexingLevel = 1
	MultiplexingLevel_MULTIPLEXING_LOW     MultiplexingLevel = 2
	MultiplexingLevel_MULTIPLEXING_MIDDLE  MultiplexingLevel = 3
	MultiplexingLevel_MULTIPLEXING_HIGH    MultiplexingLevel = 4
)

// Enum value maps for MultiplexingLevel.
var (
	MultiplexingLevel_name = map[int32]string{
		0: "MULTIPLEXING_DEFAULT",
		1: "MULTIPLEXING_OFF",
		2: "MULTIPLEXING_LOW",
		3: "MULTIPLEXING_MIDDLE",
		4: "MULTIPLEXING_HIGH",
	}
	MultiplexingLevel_value = map[string]int32{
		"MULTIPLEXING_DEFAULT": 0,
		"MULTIPLEXING_OFF":     1,
		"MULTIPLEXING_LOW":     2,
		"MULTIPLEXING_MIDDLE":  3,
		"MULTIPLEXING_HIGH":    4,
	}
)

func (x MultiplexingLevel) Enum() *MultiplexingLevel {
	p := new(MultiplexingLevel)
	*p = x
	return p
}

func (x MultiplexingLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultiplexingLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_appctl_proto_clientcfg_proto_enumTypes[0].Descriptor()
}

func (MultiplexingLevel) Type() protoreflect.EnumType {
	return &file_appctl_proto_clientcfg_proto_enumTypes[0]
}

func (x MultiplexingLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultiplexingLevel.Descriptor instead.
func (MultiplexingLevel) EnumDescriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{0}
}

type HandshakeMode int32

const (
	HandshakeMode_HANDSHAKE_DEFAULT HandshakeMode = 0
	// Client wait for proxy server to establish connection to the destination
	// before sending the payload.
	// Also known as 1-RTT.
	HandshakeMode_HANDSHAKE_STANDARD HandshakeMode = 1
	// Client send payload at the same time when connecting to the proxy server.
	// Also known as 0-RTT.
	HandshakeMode_HANDSHAKE_NO_WAIT HandshakeMode = 2
)

// Enum value maps for HandshakeMode.
var (
	HandshakeMode_name = map[int32]string{
		0: "HANDSHAKE_DEFAULT",
		1: "HANDSHAKE_STANDARD",
		2: "HANDSHAKE_NO_WAIT",
	}
	HandshakeMode_value = map[string]int32{
		"HANDSHAKE_DEFAULT":  0,
		"HANDSHAKE_STANDARD": 1,
		"HANDSHAKE_NO_WAIT":  2,
	}
)

func (x HandshakeMode) Enum() *HandshakeMode {
	p := new(HandshakeMode)
	*p = x
	return p
}

func (x HandshakeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandshakeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_appctl_proto_clientcfg_proto_enumTypes[1].Descriptor()
}

func (HandshakeMode) Type() protoreflect.EnumType {
	return &file_appctl_proto_clientcfg_proto_enumTypes[1]
}

func (x HandshakeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandshakeMode.Descriptor instead.
func (HandshakeMode) EnumDescriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{1}
}

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of known client profiles.
	Profiles []*ClientProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	// The active profile name.
	ActiveProfile *string `protobuf:"bytes,2,opt,name=activeProfile,proto3,oneof" json:"activeProfile,omitempty"`
	// The management RPC port that client is listening in localhost.
	RpcPort *int32 `protobuf:"varint,3,opt,name=rpcPort,proto3,oneof" json:"rpcPort,omitempty"`
	// The socks5 port that mieru is listening.
	Socks5Port *int32 `protobuf:"varint,4,opt,name=socks5Port,proto3,oneof" json:"socks5Port,omitempty"`
	// Client advanced settings.
	AdvancedSettings *ClientAdvancedSettings `protobuf:"bytes,5,opt,name=advancedSettings,proto3,oneof" json:"advancedSettings,omitempty"`
	// Client logging level.
	LoggingLevel *LoggingLevel `protobuf:"varint,6,opt,name=loggingLevel,proto3,enum=mieru.appctl.LoggingLevel,oneof" json:"loggingLevel,omitempty"`
	// If set, the socks5 port listens to LAN rather than localhost.
	Socks5ListenLAN *bool `protobuf:"varint,7,opt,name=socks5ListenLAN,proto3,oneof" json:"socks5ListenLAN,omitempty"`
	// The port mieru is listening to provide HTTP / HTTPS proxy.
	HttpProxyPort *int32 `protobuf:"varint,8,opt,name=httpProxyPort,proto3,oneof" json:"httpProxyPort,omitempty"`
	// If set, the HTTP proxy port listens to LAN rather than localhost.
	HttpProxyListenLAN *bool `protobuf:"varint,9,opt,name=httpProxyListenLAN,proto3,oneof" json:"httpProxyListenLAN,omitempty"`
	// A list of accounts that can authenticate mieru socks5 proxy service.
	// If the list is empty, authentication is not required.
	Socks5Authentication []*Auth `protobuf:"bytes,10,rep,name=socks5Authentication,proto3" json:"socks5Authentication,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetProfiles() []*ClientProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ClientConfig) GetActiveProfile() string {
	if x != nil && x.ActiveProfile != nil {
		return *x.ActiveProfile
	}
	return ""
}

func (x *ClientConfig) GetRpcPort() int32 {
	if x != nil && x.RpcPort != nil {
		return *x.RpcPort
	}
	return 0
}

func (x *ClientConfig) GetSocks5Port() int32 {
	if x != nil && x.Socks5Port != nil {
		return *x.Socks5Port
	}
	return 0
}

func (x *ClientConfig) GetAdvancedSettings() *ClientAdvancedSettings {
	if x != nil {
		return x.AdvancedSettings
	}
	return nil
}

func (x *ClientConfig) GetLoggingLevel() LoggingLevel {
	if x != nil && x.LoggingLevel != nil {
		return *x.LoggingLevel
	}
	return LoggingLevel_DEFAULT
}

func (x *ClientConfig) GetSocks5ListenLAN() bool {
	if x != nil && x.Socks5ListenLAN != nil {
		return *x.Socks5ListenLAN
	}
	return false
}

func (x *ClientConfig) GetHttpProxyPort() int32 {
	if x != nil && x.HttpProxyPort != nil {
		return *x.HttpProxyPort
	}
	return 0
}

func (x *ClientConfig) GetHttpProxyListenLAN() bool {
	if x != nil && x.HttpProxyListenLAN != nil {
		return *x.HttpProxyListenLAN
	}
	return false
}

func (x *ClientConfig) GetSocks5Authentication() []*Auth {
	if x != nil {
		return x.Socks5Authentication
	}
	return nil
}

type ClientProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client profile name.
	ProfileName *string `protobuf:"bytes,1,opt,name=profileName,proto3,oneof" json:"profileName,omitempty"`
	// User information.
	User *User `protobuf:"bytes,2,opt,name=user,proto3,oneof" json:"user,omitempty"`
	// A list of servers to connect.
	Servers []*ServerEndpoint `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	// Maximum transmission unit of L2 payload.
	// This setting only applies to UDP protocol egress traffic.
	Mtu *int32 `protobuf:"varint,4,opt,name=mtu,proto3,oneof" json:"mtu,omitempty"`
	// Multiplexing behaviors.
	Multiplexing *MultiplexingConfig `protobuf:"bytes,5,opt,name=multiplexing,proto3,oneof" json:"multiplexing,omitempty"`
	// Handshake mode when client open a connection.
	HandshakeMode *HandshakeMode `protobuf:"varint,6,opt,name=handshakeMode,proto3,enum=mieru.appctl.HandshakeMode,oneof" json:"handshakeMode,omitempty"`
	// Fine tune traffic behaviors.
	TrafficPattern *TrafficPattern `protobuf:"bytes,7,opt,name=trafficPattern,proto3,oneof" json:"trafficPattern,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientProfile) Reset() {
	*x = ClientProfile{}
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProfile) ProtoMessage() {}

func (x *ClientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProfile.ProtoReflect.Descriptor instead.
func (*ClientProfile) Descriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{1}
}

func (x *ClientProfile) GetProfileName() string {
	if x != nil && x.ProfileName != nil {
		return *x.ProfileName
	}
	return ""
}

func (x *ClientProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ClientProfile) GetServers() []*ServerEndpoint {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ClientProfile) GetMtu() int32 {
	if x != nil && x.Mtu != nil {
		return *x.Mtu
	}
	return 0
}

func (x *ClientProfile) GetMultiplexing() *MultiplexingConfig {
	if x != nil {
		return x.Multiplexing
	}
	return nil
}

func (x *ClientProfile) GetHandshakeMode() HandshakeMode {
	if x != nil && x.HandshakeMode != nil {
		return *x.HandshakeMode
	}
	return HandshakeMode_HANDSHAKE_DEFAULT
}

func (x *ClientProfile) GetTrafficPattern() *TrafficPattern {
	if x != nil {
		return x.TrafficPattern
	}
	return nil
}

type ServerEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String representation of IP address.
	// It can be either IPv4 or IPv6.
	IpAddress *string `protobuf:"bytes,1,opt,name=ipAddress,proto3,oneof" json:"ipAddress,omitempty"`
	// Server's full qualified domain name.
	// When this is set, the `ipAddress` field is ignored.
	DomainName *string `protobuf:"bytes,2,opt,name=domainName,proto3,oneof" json:"domainName,omitempty"`
	// Server's port-protocol bindings.
	PortBindings  []*PortBinding `protobuf:"bytes,3,rep,name=portBindings,proto3" json:"portBindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEndpoint) Reset() {
	*x = ServerEndpoint{}
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEndpoint) ProtoMessage() {}

func (x *ServerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEndpoint.ProtoReflect.Descriptor instead.
func (*ServerEndpoint) Descriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{2}
}

func (x *ServerEndpoint) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *ServerEndpoint) GetDomainName() string {
	if x != nil && x.DomainName != nil {
		return *x.DomainName
	}
	return ""
}

func (x *ServerEndpoint) GetPortBindings() []*PortBinding {
	if x != nil {
		return x.PortBindings
	}
	return nil
}

type MultiplexingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How frequent a network connection is reused.
	Level         *MultiplexingLevel `protobuf:"varint,1,opt,name=level,proto3,enum=mieru.appctl.MultiplexingLevel,oneof" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplexingConfig) Reset() {
	*x = MultiplexingConfig{}
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplexingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexingConfig) ProtoMessage() {}

func (x *MultiplexingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexingConfig.ProtoReflect.Descriptor instead.
func (*MultiplexingConfig) Descriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{3}
}

func (x *MultiplexingConfig) GetLevel() MultiplexingLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return MultiplexingLevel_MULTIPLEXING_DEFAULT
}

type ClientAdvancedSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Do not check update when client is started.
	NoCheckUpdate *bool `protobuf:"varint,1,opt,name=noCheckUpdate,proto3,oneof" json:"noCheckUpdate,omitempty"`
	// The interval to log metrics.
	// Examples: 30s, 5m, 2h.
	// If empty, the default interval is used.
	MetricsLoggingInterval *string `protobuf:"bytes,2,opt,name=metricsLoggingInterval,proto3,oneof" json:"metricsLoggingInterval,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientAdvancedSettings) Reset() {
	*x = ClientAdvancedSettings{}
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAdvancedSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAdvancedSettings) ProtoMessage() {}

func (x *ClientAdvancedSettings) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_clientcfg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAdvancedSettings.ProtoReflect.Descriptor instead.
func (*ClientAdvancedSettings) Descriptor() ([]byte, []int) {
	return file_appctl_proto_clientcfg_proto_rawDescGZIP(), []int{4}
}

func (x *ClientAdvancedSettings) GetNoCheckUpdate() bool {
	if x != nil && x.NoCheckUpdate != nil {
		return *x.NoCheckUpdate
	}
	return false
}

func (x *ClientAdvancedSettings) GetMetricsLoggingInterval() string {
	if x != nil && x.MetricsLoggingInterval != nil {
		return *x.MetricsLoggingInterval
	}
	return ""
}

var File_appctl_proto_clientcfg_proto protoreflect.FileDescriptor

const file_appctl_proto_clientcfg_proto_rawDesc = "" +
	"\n" +
	"\x1cappctl/proto/clientcfg.proto\x12\fmieru.appctl\x1a\x17appctl/proto/base.proto\"\xb9\x05\n" +
	"\fClientConfig\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.mieru.appctl.ClientProfileR\bprofiles\x12)\n" +
	"\ractiveProfile\x18\x02 \x01(\tH\x00R\ractiveProfile\x88\x01\x01\x12\x1d\n" +
	"\arpcPort\x18\x03 \x01(\x05H\x01R\arpcPort\x88\x01\x01\x12#\n" +
	"\n" +
	"socks5Port\x18\x04 \x01(\x05H\x02R\n" +
	"socks5Port\x88\x01\x01\x12U\n" +
	"\x10advancedSettings\x18\x05 \x01(\v2$.mieru.appctl.ClientAdvancedSettingsH\x03R\x10advancedSettings\x88\x01\x01\x12C\n" +
	"\floggingLevel\x18\x06 \x01(\x0e2\x1a.mieru.appctl.LoggingLevelH\x04R\floggingLevel\x88\x01\x01\x12-\n" +
	"\x0fsocks5ListenLAN\x18\a \x01(\bH\x05R\x0fsocks5ListenLAN\x88\x01\x01\x12)\n" +
	"\rhttpProxyPort\x18\b \x01(\x05H\x06R\rhttpProxyPort\x88\x01\x01\x123\n" +
	"\x12httpProxyListenLAN\x18\t \x01(\bH\aR\x12httpProxyListenLAN\x88\x01\x01\x12F\n" +
	"\x14socks5Authentication\x18\n" +
	" \x03(\v2\x12.mieru.appctl.AuthR\x14socks5AuthenticationB\x10\n" +
	"\x0e_activeProfileB\n" +
	"\n" +
	"\b_rpcPortB\r\n" +
	"\v_socks5PortB\x13\n" +
	"\x11_advancedSettingsB\x0f\n" +
	"\r_loggingLevelB\x12\n" +
	"\x10_socks5ListenLANB\x10\n" +
	"\x0e_httpProxyPortB\x15\n" +
	"\x13_httpProxyListenLAN\"\xe7\x03\n" +
	"\rClientProfile\x12%\n" +
	"\vprofileName\x18\x01 \x01(\tH\x00R\vprofileName\x88\x01\x01\x12+\n" +
	"\x04user\x18\x02 \x01(\v2\x12.mieru.appctl.UserH\x01R\x04user\x88\x01\x01\x126\n" +
	"\aservers\x18\x03 \x03(\v2\x1c.mieru.appctl.ServerEndpointR\aservers\x12\x15\n" +
	"\x03mtu\x18\x04 \x01(\x05H\x02R\x03mtu\x88\x01\x01\x12I\n" +
	"\fmultiplexing\x18\x05 \x01(\v2 .mieru.appctl.MultiplexingConfigH\x03R\fmultiplexing\x88\x01\x01\x12F\n" +
	"\rhandshakeMode\x18\x06 \x01(\x0e2\x1b.mieru.appctl.HandshakeModeH\x04R\rhandshakeMode\x88\x01\x01\x12I\n" +
	"\x0etrafficPattern\x18\a \x01(\v2\x1c.mieru.appctl.TrafficPatternH\x05R\x0etrafficPattern\x88\x01\x01B\x0e\n" +
	"\f_profileNameB\a\n" +
	"\x05_userB\x06\n" +
	"\x04_mtuB\x0f\n" +
	"\r_multiplexingB\x10\n" +
	"\x0e_handshakeModeB\x11\n" +
	"\x0f_trafficPattern\"\xb4\x01\n" +
	"\x0eServerEndpoint\x12!\n" +
	"\tipAddress\x18\x01 \x01(\tH\x00R\tipAddress\x88\x01\x01\x12#\n" +
	"\n" +
	"domainName\x18\x02 \x01(\tH\x01R\n" +
	"domainName\x88\x01\x01\x12=\n" +
	"\fportBindings\x18\x03 \x03(\v2\x19.mieru.appctl.PortBindingR\fportBindingsB\f\n" +
	"\n" +
	"_ipAddressB\r\n" +
	"\v_domainName\"Z\n" +
	"\x12MultiplexingConfig\x12:\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1f.mieru.appctl.MultiplexingLevelH\x00R\x05level\x88\x01\x01B\b\n" +
	"\x06_level\"\xad\x01\n" +
	"\x16ClientAdvancedSettings\x12)\n" +
	"\rnoCheckUpdate\x18\x01 \x01(\bH\x00R\rnoCheckUpdate\x88\x01\x01\x12;\n" +
	"\x16metricsLoggingInterval\x18\x02 \x01(\tH\x01R\x16metricsLoggingInterval\x88\x01\x01B\x10\n" +
	"\x0e_noCheckUpdateB\x19\n" +
	"\x17_metricsLoggingInterval*\x89\x01\n" +
	"\x11MultiplexingLevel\x12\x18\n" +
	"\x14MULTIPLEXING_DEFAULT\x10\x00\x12\x14\n" +
	"\x10MULTIPLEXING_OFF\x10\x01\x12\x14\n" +
	"\x10MULTIPLEXING_LOW\x10\x02\x12\x17\n" +
	"\x13MULTIPLEXING_MIDDLE\x10\x03\x12\x15\n" +
	"\x11MULTIPLEXING_HIGH\x10\x04*U\n" +
	"\rHandshakeMode\x12\x15\n" +
	"\x11HANDSHAKE_DEFAULT\x10\x00\x12\x16\n" +
	"\x12HANDSHAKE_STANDARD\x10\x01\x12\x15\n" +
	"\x11HANDSHAKE_NO_WAIT\x10\x02B0Z.github.com/enfein/mieru/v3/pkg/appctl/appctlpbb\x06proto3"

var (
	file_appctl_proto_clientcfg_proto_rawDescOnce sync.Once
	file_appctl_proto_clientcfg_proto_rawDescData []byte
)

func file_appctl_proto_clientcfg_proto_rawDescGZIP() []byte {
	file_appctl_proto_clientcfg_proto_rawDescOnce.Do(func() {
		file_appctl_proto_clientcfg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appctl_proto_clientcfg_proto_rawDesc), len(file_appctl_proto_clientcfg_proto_rawDesc)))
	})
	return file_appctl_proto_clientcfg_proto_rawDescData
}

var file_appctl_proto_clientcfg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_appctl_proto_clientcfg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_appctl_proto_clientcfg_proto_goTypes = []any{
	(MultiplexingLevel)(0),         // 0: mieru.appctl.MultiplexingLevel
	(HandshakeMode)(0),             // 1: mieru.appctl.HandshakeMode
	(*ClientConfig)(nil),           // 2: mieru.appctl.ClientConfig
	(*ClientProfile)(nil),          // 3: mieru.appctl.ClientProfile
	(*ServerEndpoint)(nil),         // 4: mieru.appctl.ServerEndpoint
	(*MultiplexingConfig)(nil),     // 5: mieru.appctl.MultiplexingConfig
	(*ClientAdvancedSettings)(nil), // 6: mieru.appctl.ClientAdvancedSettings
	(LoggingLevel)(0),              // 7: mieru.appctl.LoggingLevel
	(*Auth)(nil),                   // 8: mieru.appctl.Auth
	(*User)(nil),                   // 9: mieru.appctl.User
	(*TrafficPattern)(nil),         // 10: mieru.appctl.TrafficPattern
	(*PortBinding)(nil),            // 11: mieru.appctl.PortBinding
}
var file_appctl_proto_clientcfg_proto_depIdxs = []int32{
	3,  // 0: mieru.appctl.ClientConfig.profiles:type_name -> mieru.appctl.ClientProfile
	6,  // 1: mieru.appctl.ClientConfig.advancedSettings:type_name -> mieru.appctl.ClientAdvancedSettings
	7,  // 2: mieru.appctl.ClientConfig.loggingLevel:type_name -> mieru.appctl.LoggingLevel
	8,  // 3: mieru.appctl.ClientConfig.socks5Authentication:type_name -> mieru.appctl.Auth
	9,  // 4: mieru.appctl.ClientProfile.user:type_name -> mieru.appctl.User
	4,  // 5: mieru.appctl.ClientProfile.servers:type_name -> mieru.appctl.ServerEndpoint
	5,  // 6: mieru.appctl.ClientProfile.multiplexing:type_name -> mieru.appctl.MultiplexingConfig
	1,  // 7: mieru.appctl.ClientProfile.handshakeMode:type_name -> mieru.appctl.HandshakeMode
	10, // 8: mieru.appctl.ClientProfile.trafficPattern:type_name -> mieru.appctl.TrafficPattern
	11, // 9: mieru.appctl.ServerEndpoint.portBindings:type_name -> mieru.appctl.PortBinding
	0,  // 10: mieru.appctl.MultiplexingConfig.level:type_name -> mieru.appctl.MultiplexingLevel
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_appctl_proto_clientcfg_proto_init() }
func file_appctl_proto_clientcfg_proto_init() {
	if File_appctl_proto_clientcfg_proto != nil {
		return
	}
	file_appctl_proto_base_proto_init()
	file_appctl_proto_clientcfg_proto_msgTypes[0].OneofWrappers = []any{}
	file_appctl_proto_clientcfg_proto_msgTypes[1].OneofWrappers = []any{}
	file_appctl_proto_clientcfg_proto_msgTypes[2].OneofWrappers = []any{}
	file_appctl_proto_clientcfg_proto_msgTypes[3].OneofWrappers = []any{}
	file_appctl_proto_clientcfg_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appctl_proto_clientcfg_proto_rawDesc), len(file_appctl_proto_clientcfg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appctl_proto_clientcfg_proto_goTypes,
		DependencyIndexes: file_appctl_proto_clientcfg_proto_depIdxs,
		EnumInfos:         file_appctl_proto_clientcfg_proto_enumTypes,
		MessageInfos:      file_appctl_proto_clientcfg_proto_msgTypes,
	}.Build()
	File_appctl_proto_clientcfg_proto = out.File
	file_appctl_proto_clientcfg_proto_goTypes = nil
	file_appctl_proto_clientcfg_proto_depIdxs = nil
}
