// Copyright (C) 2023  mieru authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: multiplexing.proto

package appctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplexingLevel int32

const (
	MultiplexingLevel_MULTIPLEXING_DEFAULT MultiplexingLevel = 0
	MultiplexingLevel_MULTIPLEXING_OFF     MultiplexingLevel = 1
	MultiplexingLevel_MULTIPLEXING_LOW     MultiplexingLevel = 2
	MultiplexingLevel_MULTIPLEXING_MIDDLE  MultiplexingLevel = 3
	MultiplexingLevel_MULTIPLEXING_HIGH    MultiplexingLevel = 4
)

// Enum value maps for MultiplexingLevel.
var (
	MultiplexingLevel_name = map[int32]string{
		0: "MULTIPLEXING_DEFAULT",
		1: "MULTIPLEXING_OFF",
		2: "MULTIPLEXING_LOW",
		3: "MULTIPLEXING_MIDDLE",
		4: "MULTIPLEXING_HIGH",
	}
	MultiplexingLevel_value = map[string]int32{
		"MULTIPLEXING_DEFAULT": 0,
		"MULTIPLEXING_OFF":     1,
		"MULTIPLEXING_LOW":     2,
		"MULTIPLEXING_MIDDLE":  3,
		"MULTIPLEXING_HIGH":    4,
	}
)

func (x MultiplexingLevel) Enum() *MultiplexingLevel {
	p := new(MultiplexingLevel)
	*p = x
	return p
}

func (x MultiplexingLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultiplexingLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_multiplexing_proto_enumTypes[0].Descriptor()
}

func (MultiplexingLevel) Type() protoreflect.EnumType {
	return &file_multiplexing_proto_enumTypes[0]
}

func (x MultiplexingLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultiplexingLevel.Descriptor instead.
func (MultiplexingLevel) EnumDescriptor() ([]byte, []int) {
	return file_multiplexing_proto_rawDescGZIP(), []int{0}
}

type MultiplexingConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// How frequent a network connection is reused.
	Level *MultiplexingLevel `protobuf:"varint,1,opt,name=level,proto3,enum=appctl.MultiplexingLevel,oneof" json:"level,omitempty"`
}

func (x *MultiplexingConfig) Reset() {
	*x = MultiplexingConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplexing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplexingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexingConfig) ProtoMessage() {}

func (x *MultiplexingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_multiplexing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexingConfig.ProtoReflect.Descriptor instead.
func (*MultiplexingConfig) Descriptor() ([]byte, []int) {
	return file_multiplexing_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplexingConfig) GetLevel() MultiplexingLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return MultiplexingLevel_MULTIPLEXING_DEFAULT
}

var File_multiplexing_proto protoreflect.FileDescriptor

var file_multiplexing_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x70, 0x63, 0x74, 0x6c, 0x22, 0x54, 0x0a, 0x12,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x34, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x70, 0x63, 0x74, 0x6c, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x2a, 0x89, 0x01, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x78,
	0x69, 0x6e, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x55, 0x4c, 0x54,
	0x49, 0x50, 0x4c, 0x45, 0x58, 0x49, 0x4e, 0x47, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50, 0x4c, 0x45, 0x58, 0x49,
	0x4e, 0x47, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x55, 0x4c, 0x54,
	0x49, 0x50, 0x4c, 0x45, 0x58, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x12, 0x17,
	0x0a, 0x13, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50, 0x4c, 0x45, 0x58, 0x49, 0x4e, 0x47, 0x5f, 0x4d,
	0x49, 0x44, 0x44, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x55, 0x4c, 0x54, 0x49,
	0x50, 0x4c, 0x45, 0x58, 0x49, 0x4e, 0x47, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10, 0x04, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x66,
	0x65, 0x69, 0x6e, 0x2f, 0x6d, 0x69, 0x65, 0x72, 0x75, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x70, 0x63, 0x74, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x63, 0x74, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiplexing_proto_rawDescOnce sync.Once
	file_multiplexing_proto_rawDescData = file_multiplexing_proto_rawDesc
)

func file_multiplexing_proto_rawDescGZIP() []byte {
	file_multiplexing_proto_rawDescOnce.Do(func() {
		file_multiplexing_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiplexing_proto_rawDescData)
	})
	return file_multiplexing_proto_rawDescData
}

var file_multiplexing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_multiplexing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multiplexing_proto_goTypes = []interface{}{
	(MultiplexingLevel)(0),     // 0: appctl.MultiplexingLevel
	(*MultiplexingConfig)(nil), // 1: appctl.MultiplexingConfig
}
var file_multiplexing_proto_depIdxs = []int32{
	0, // 0: appctl.MultiplexingConfig.level:type_name -> appctl.MultiplexingLevel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_multiplexing_proto_init() }
func file_multiplexing_proto_init() {
	if File_multiplexing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiplexing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplexingConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_multiplexing_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiplexing_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multiplexing_proto_goTypes,
		DependencyIndexes: file_multiplexing_proto_depIdxs,
		EnumInfos:         file_multiplexing_proto_enumTypes,
		MessageInfos:      file_multiplexing_proto_msgTypes,
	}.Build()
	File_multiplexing_proto = out.File
	file_multiplexing_proto_rawDesc = nil
	file_multiplexing_proto_goTypes = nil
	file_multiplexing_proto_depIdxs = nil
}
