// Copyright (C) 2021  mieru authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: appctl/proto/servercfg.proto

package appctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyProtocol int32

const (
	ProxyProtocol_UNKNOWN_PROXY_PROTOCOL ProxyProtocol = 0
	ProxyProtocol_SOCKS5_PROXY_PROTOCOL  ProxyProtocol = 1
)

// Enum value maps for ProxyProtocol.
var (
	ProxyProtocol_name = map[int32]string{
		0: "UNKNOWN_PROXY_PROTOCOL",
		1: "SOCKS5_PROXY_PROTOCOL",
	}
	ProxyProtocol_value = map[string]int32{
		"UNKNOWN_PROXY_PROTOCOL": 0,
		"SOCKS5_PROXY_PROTOCOL":  1,
	}
)

func (x ProxyProtocol) Enum() *ProxyProtocol {
	p := new(ProxyProtocol)
	*p = x
	return p
}

func (x ProxyProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_appctl_proto_servercfg_proto_enumTypes[0].Descriptor()
}

func (ProxyProtocol) Type() protoreflect.EnumType {
	return &file_appctl_proto_servercfg_proto_enumTypes[0]
}

func (x ProxyProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyProtocol.Descriptor instead.
func (ProxyProtocol) EnumDescriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{0}
}

type EgressAction int32

const (
	// Use proxy to connect to the destination.
	EgressAction_PROXY EgressAction = 0
	// Directly connect to the destination.
	EgressAction_DIRECT EgressAction = 1
	// Do not connect to the destination.
	EgressAction_REJECT EgressAction = 2
)

// Enum value maps for EgressAction.
var (
	EgressAction_name = map[int32]string{
		0: "PROXY",
		1: "DIRECT",
		2: "REJECT",
	}
	EgressAction_value = map[string]int32{
		"PROXY":  0,
		"DIRECT": 1,
		"REJECT": 2,
	}
)

func (x EgressAction) Enum() *EgressAction {
	p := new(EgressAction)
	*p = x
	return p
}

func (x EgressAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressAction) Descriptor() protoreflect.EnumDescriptor {
	return file_appctl_proto_servercfg_proto_enumTypes[1].Descriptor()
}

func (EgressAction) Type() protoreflect.EnumType {
	return &file_appctl_proto_servercfg_proto_enumTypes[1]
}

func (x EgressAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressAction.Descriptor instead.
func (EgressAction) EnumDescriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{1}
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server's port-protocol bindings.
	PortBindings []*PortBinding `protobuf:"bytes,1,rep,name=portBindings,proto3" json:"portBindings,omitempty"`
	// A list of registered users.
	Users []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	// Server advanced settings.
	AdvancedSettings *ServerAdvancedSettings `protobuf:"bytes,3,opt,name=advancedSettings,proto3,oneof" json:"advancedSettings,omitempty"`
	// Server logging level.
	LoggingLevel *LoggingLevel `protobuf:"varint,4,opt,name=loggingLevel,proto3,enum=mieru.appctl.LoggingLevel,oneof" json:"loggingLevel,omitempty"`
	// Maximum transmission unit of L2 payload.
	// This setting only applies to UDP protocol egress traffic.
	Mtu *int32 `protobuf:"varint,5,opt,name=mtu,proto3,oneof" json:"mtu,omitempty"`
	// Egress proxies and rules.
	Egress *Egress `protobuf:"bytes,6,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	// How to resolve IP address when the client send a request
	// with a domain name.
	Dns *DNS `protobuf:"bytes,7,opt,name=dns,proto3,oneof" json:"dns,omitempty"`
	// Fine tune traffic behaviors.
	TrafficPattern *TrafficPattern `protobuf:"bytes,8,opt,name=trafficPattern,proto3,oneof" json:"trafficPattern,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetPortBindings() []*PortBinding {
	if x != nil {
		return x.PortBindings
	}
	return nil
}

func (x *ServerConfig) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetAdvancedSettings() *ServerAdvancedSettings {
	if x != nil {
		return x.AdvancedSettings
	}
	return nil
}

func (x *ServerConfig) GetLoggingLevel() LoggingLevel {
	if x != nil && x.LoggingLevel != nil {
		return *x.LoggingLevel
	}
	return LoggingLevel_DEFAULT
}

func (x *ServerConfig) GetMtu() int32 {
	if x != nil && x.Mtu != nil {
		return *x.Mtu
	}
	return 0
}

func (x *ServerConfig) GetEgress() *Egress {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *ServerConfig) GetDns() *DNS {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *ServerConfig) GetTrafficPattern() *TrafficPattern {
	if x != nil {
		return x.TrafficPattern
	}
	return nil
}

type ServerAdvancedSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interval to log metrics.
	// Examples: 30s, 5m, 2h.
	// If empty, the default interval is used.
	MetricsLoggingInterval *string `protobuf:"bytes,2,opt,name=metricsLoggingInterval,proto3,oneof" json:"metricsLoggingInterval,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServerAdvancedSettings) Reset() {
	*x = ServerAdvancedSettings{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAdvancedSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAdvancedSettings) ProtoMessage() {}

func (x *ServerAdvancedSettings) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAdvancedSettings.ProtoReflect.Descriptor instead.
func (*ServerAdvancedSettings) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{1}
}

func (x *ServerAdvancedSettings) GetMetricsLoggingInterval() string {
	if x != nil && x.MetricsLoggingInterval != nil {
		return *x.MetricsLoggingInterval
	}
	return ""
}

type Egress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of proxies.
	Proxies []*EgressProxy `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	// A list of rules.
	// If no rule is matched, the default action is DIRECT.
	Rules         []*EgressRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Egress) Reset() {
	*x = Egress{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Egress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Egress) ProtoMessage() {}

func (x *Egress) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Egress.ProtoReflect.Descriptor instead.
func (*Egress) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{2}
}

func (x *Egress) GetProxies() []*EgressProxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *Egress) GetRules() []*EgressRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type EgressProxy struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Protocol *ProxyProtocol         `protobuf:"varint,2,opt,name=protocol,proto3,enum=mieru.appctl.ProxyProtocol,oneof" json:"protocol,omitempty"`
	// Proxy IP address or domain name.
	Host *string `protobuf:"bytes,3,opt,name=host,proto3,oneof" json:"host,omitempty"`
	// Proxy port number.
	Port *int32 `protobuf:"varint,4,opt,name=port,proto3,oneof" json:"port,omitempty"`
	// Credential to authenticate egress socks5 proxy.
	// If the proxy protocol is not socks5, this is ignored.
	Socks5Authentication *Auth `protobuf:"bytes,5,opt,name=socks5Authentication,proto3,oneof" json:"socks5Authentication,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EgressProxy) Reset() {
	*x = EgressProxy{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressProxy) ProtoMessage() {}

func (x *EgressProxy) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressProxy.ProtoReflect.Descriptor instead.
func (*EgressProxy) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{3}
}

func (x *EgressProxy) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EgressProxy) GetProtocol() ProxyProtocol {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ProxyProtocol_UNKNOWN_PROXY_PROTOCOL
}

func (x *EgressProxy) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *EgressProxy) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *EgressProxy) GetSocks5Authentication() *Auth {
	if x != nil {
		return x.Socks5Authentication
	}
	return nil
}

type EgressRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of CIDR to match the rule.
	// Use "*" to match all IP addresses.
	IpRanges []string `protobuf:"bytes,1,rep,name=ipRanges,proto3" json:"ipRanges,omitempty"`
	// A list of domain names to match the rule.
	// Use "*" to match all domain names.
	DomainNames []string `protobuf:"bytes,2,rep,name=domainNames,proto3" json:"domainNames,omitempty"`
	// The action to do when the rule is matched.
	Action *EgressAction `protobuf:"varint,3,opt,name=action,proto3,enum=mieru.appctl.EgressAction,oneof" json:"action,omitempty"`
	// The list of proxies to connect.
	// This must not be empty when the action is PROXY.
	// When multiple proxies are provided, a random one is selected
	// for each request.
	ProxyNames    []string `protobuf:"bytes,4,rep,name=proxyNames,proto3" json:"proxyNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRule) Reset() {
	*x = EgressRule{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRule) ProtoMessage() {}

func (x *EgressRule) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRule.ProtoReflect.Descriptor instead.
func (*EgressRule) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{4}
}

func (x *EgressRule) GetIpRanges() []string {
	if x != nil {
		return x.IpRanges
	}
	return nil
}

func (x *EgressRule) GetDomainNames() []string {
	if x != nil {
		return x.DomainNames
	}
	return nil
}

func (x *EgressRule) GetAction() EgressAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return EgressAction_PROXY
}

func (x *EgressRule) GetProxyNames() []string {
	if x != nil {
		return x.ProxyNames
	}
	return nil
}

type DNS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pick up IP address from IP version preference.
	DualStack     *DualStack `protobuf:"varint,1,opt,name=dualStack,proto3,enum=mieru.appctl.DualStack,oneof" json:"dualStack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS) Reset() {
	*x = DNS{}
	mi := &file_appctl_proto_servercfg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS) ProtoMessage() {}

func (x *DNS) ProtoReflect() protoreflect.Message {
	mi := &file_appctl_proto_servercfg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS.ProtoReflect.Descriptor instead.
func (*DNS) Descriptor() ([]byte, []int) {
	return file_appctl_proto_servercfg_proto_rawDescGZIP(), []int{5}
}

func (x *DNS) GetDualStack() DualStack {
	if x != nil && x.DualStack != nil {
		return *x.DualStack
	}
	return DualStack_USE_FIRST_IP
}

var File_appctl_proto_servercfg_proto protoreflect.FileDescriptor

const file_appctl_proto_servercfg_proto_rawDesc = "" +
	"\n" +
	"\x1cappctl/proto/servercfg.proto\x12\fmieru.appctl\x1a\x17appctl/proto/base.proto\"\xa6\x04\n" +
	"\fServerConfig\x12=\n" +
	"\fportBindings\x18\x01 \x03(\v2\x19.mieru.appctl.PortBindingR\fportBindings\x12(\n" +
	"\x05users\x18\x02 \x03(\v2\x12.mieru.appctl.UserR\x05users\x12U\n" +
	"\x10advancedSettings\x18\x03 \x01(\v2$.mieru.appctl.ServerAdvancedSettingsH\x00R\x10advancedSettings\x88\x01\x01\x12C\n" +
	"\floggingLevel\x18\x04 \x01(\x0e2\x1a.mieru.appctl.LoggingLevelH\x01R\floggingLevel\x88\x01\x01\x12\x15\n" +
	"\x03mtu\x18\x05 \x01(\x05H\x02R\x03mtu\x88\x01\x01\x121\n" +
	"\x06egress\x18\x06 \x01(\v2\x14.mieru.appctl.EgressH\x03R\x06egress\x88\x01\x01\x12(\n" +
	"\x03dns\x18\a \x01(\v2\x11.mieru.appctl.DNSH\x04R\x03dns\x88\x01\x01\x12I\n" +
	"\x0etrafficPattern\x18\b \x01(\v2\x1c.mieru.appctl.TrafficPatternH\x05R\x0etrafficPattern\x88\x01\x01B\x13\n" +
	"\x11_advancedSettingsB\x0f\n" +
	"\r_loggingLevelB\x06\n" +
	"\x04_mtuB\t\n" +
	"\a_egressB\x06\n" +
	"\x04_dnsB\x11\n" +
	"\x0f_trafficPattern\"v\n" +
	"\x16ServerAdvancedSettings\x12;\n" +
	"\x16metricsLoggingInterval\x18\x02 \x01(\tH\x00R\x16metricsLoggingInterval\x88\x01\x01B\x19\n" +
	"\x17_metricsLoggingIntervalJ\x04\b\x01\x10\x02\"m\n" +
	"\x06Egress\x123\n" +
	"\aproxies\x18\x01 \x03(\v2\x19.mieru.appctl.EgressProxyR\aproxies\x12.\n" +
	"\x05rules\x18\x02 \x03(\v2\x18.mieru.appctl.EgressRuleR\x05rules\"\xa4\x02\n" +
	"\vEgressProxy\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12<\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x1b.mieru.appctl.ProxyProtocolH\x01R\bprotocol\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\x03 \x01(\tH\x02R\x04host\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x04 \x01(\x05H\x03R\x04port\x88\x01\x01\x12K\n" +
	"\x14socks5Authentication\x18\x05 \x01(\v2\x12.mieru.appctl.AuthH\x04R\x14socks5Authentication\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_protocolB\a\n" +
	"\x05_hostB\a\n" +
	"\x05_portB\x17\n" +
	"\x15_socks5Authentication\"\xae\x01\n" +
	"\n" +
	"EgressRule\x12\x1a\n" +
	"\bipRanges\x18\x01 \x03(\tR\bipRanges\x12 \n" +
	"\vdomainNames\x18\x02 \x03(\tR\vdomainNames\x127\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1a.mieru.appctl.EgressActionH\x00R\x06action\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"proxyNames\x18\x04 \x03(\tR\n" +
	"proxyNamesB\t\n" +
	"\a_action\"O\n" +
	"\x03DNS\x12:\n" +
	"\tdualStack\x18\x01 \x01(\x0e2\x17.mieru.appctl.DualStackH\x00R\tdualStack\x88\x01\x01B\f\n" +
	"\n" +
	"_dualStack*F\n" +
	"\rProxyProtocol\x12\x1a\n" +
	"\x16UNKNOWN_PROXY_PROTOCOL\x10\x00\x12\x19\n" +
	"\x15SOCKS5_PROXY_PROTOCOL\x10\x01*1\n" +
	"\fEgressAction\x12\t\n" +
	"\x05PROXY\x10\x00\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x01\x12\n" +
	"\n" +
	"\x06REJECT\x10\x02B0Z.github.com/enfein/mieru/v3/pkg/appctl/appctlpbb\x06proto3"

var (
	file_appctl_proto_servercfg_proto_rawDescOnce sync.Once
	file_appctl_proto_servercfg_proto_rawDescData []byte
)

func file_appctl_proto_servercfg_proto_rawDescGZIP() []byte {
	file_appctl_proto_servercfg_proto_rawDescOnce.Do(func() {
		file_appctl_proto_servercfg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appctl_proto_servercfg_proto_rawDesc), len(file_appctl_proto_servercfg_proto_rawDesc)))
	})
	return file_appctl_proto_servercfg_proto_rawDescData
}

var file_appctl_proto_servercfg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_appctl_proto_servercfg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_appctl_proto_servercfg_proto_goTypes = []any{
	(ProxyProtocol)(0),             // 0: mieru.appctl.ProxyProtocol
	(EgressAction)(0),              // 1: mieru.appctl.EgressAction
	(*ServerConfig)(nil),           // 2: mieru.appctl.ServerConfig
	(*ServerAdvancedSettings)(nil), // 3: mieru.appctl.ServerAdvancedSettings
	(*Egress)(nil),                 // 4: mieru.appctl.Egress
	(*EgressProxy)(nil),            // 5: mieru.appctl.EgressProxy
	(*EgressRule)(nil),             // 6: mieru.appctl.EgressRule
	(*DNS)(nil),                    // 7: mieru.appctl.DNS
	(*PortBinding)(nil),            // 8: mieru.appctl.PortBinding
	(*User)(nil),                   // 9: mieru.appctl.User
	(LoggingLevel)(0),              // 10: mieru.appctl.LoggingLevel
	(*TrafficPattern)(nil),         // 11: mieru.appctl.TrafficPattern
	(*Auth)(nil),                   // 12: mieru.appctl.Auth
	(DualStack)(0),                 // 13: mieru.appctl.DualStack
}
var file_appctl_proto_servercfg_proto_depIdxs = []int32{
	8,  // 0: mieru.appctl.ServerConfig.portBindings:type_name -> mieru.appctl.PortBinding
	9,  // 1: mieru.appctl.ServerConfig.users:type_name -> mieru.appctl.User
	3,  // 2: mieru.appctl.ServerConfig.advancedSettings:type_name -> mieru.appctl.ServerAdvancedSettings
	10, // 3: mieru.appctl.ServerConfig.loggingLevel:type_name -> mieru.appctl.LoggingLevel
	4,  // 4: mieru.appctl.ServerConfig.egress:type_name -> mieru.appctl.Egress
	7,  // 5: mieru.appctl.ServerConfig.dns:type_name -> mieru.appctl.DNS
	11, // 6: mieru.appctl.ServerConfig.trafficPattern:type_name -> mieru.appctl.TrafficPattern
	5,  // 7: mieru.appctl.Egress.proxies:type_name -> mieru.appctl.EgressProxy
	6,  // 8: mieru.appctl.Egress.rules:type_name -> mieru.appctl.EgressRule
	0,  // 9: mieru.appctl.EgressProxy.protocol:type_name -> mieru.appctl.ProxyProtocol
	12, // 10: mieru.appctl.EgressProxy.socks5Authentication:type_name -> mieru.appctl.Auth
	1,  // 11: mieru.appctl.EgressRule.action:type_name -> mieru.appctl.EgressAction
	13, // 12: mieru.appctl.DNS.dualStack:type_name -> mieru.appctl.DualStack
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_appctl_proto_servercfg_proto_init() }
func file_appctl_proto_servercfg_proto_init() {
	if File_appctl_proto_servercfg_proto != nil {
		return
	}
	file_appctl_proto_base_proto_init()
	file_appctl_proto_servercfg_proto_msgTypes[0].OneofWrappers = []any{}
	file_appctl_proto_servercfg_proto_msgTypes[1].OneofWrappers = []any{}
	file_appctl_proto_servercfg_proto_msgTypes[3].OneofWrappers = []any{}
	file_appctl_proto_servercfg_proto_msgTypes[4].OneofWrappers = []any{}
	file_appctl_proto_servercfg_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appctl_proto_servercfg_proto_rawDesc), len(file_appctl_proto_servercfg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appctl_proto_servercfg_proto_goTypes,
		DependencyIndexes: file_appctl_proto_servercfg_proto_depIdxs,
		EnumInfos:         file_appctl_proto_servercfg_proto_enumTypes,
		MessageInfos:      file_appctl_proto_servercfg_proto_msgTypes,
	}.Build()
	File_appctl_proto_servercfg_proto = out.File
	file_appctl_proto_servercfg_proto_goTypes = nil
	file_appctl_proto_servercfg_proto_depIdxs = nil
}
