// Copyright (C) 2024  mieru authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: version/updater/proto/history.proto

package updaterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*UpdateRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHistory) Reset() {
	*x = UpdateHistory{}
	mi := &file_version_updater_proto_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistory) ProtoMessage() {}

func (x *UpdateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_version_updater_proto_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistory.ProtoReflect.Descriptor instead.
func (*UpdateHistory) Descriptor() ([]byte, []int) {
	return file_version_updater_proto_history_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateHistory) GetRecords() []*UpdateRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpdateRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time in UNIX second when this record is created.
	TimeUnix *int64 `protobuf:"varint,1,opt,name=timeUnix,proto3,oneof" json:"timeUnix,omitempty"`
	// The software version that runs the check update.
	Version *string `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// The latest software version, if found.
	LatestVersion *string `protobuf:"bytes,3,opt,name=latestVersion,proto3,oneof" json:"latestVersion,omitempty"`
	// If a new release is found.
	NewReleaseFound *bool `protobuf:"varint,4,opt,name=newReleaseFound,proto3,oneof" json:"newReleaseFound,omitempty"`
	// An error message when check update fail.
	Error         *string `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecord) Reset() {
	*x = UpdateRecord{}
	mi := &file_version_updater_proto_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecord) ProtoMessage() {}

func (x *UpdateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_version_updater_proto_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecord.ProtoReflect.Descriptor instead.
func (*UpdateRecord) Descriptor() ([]byte, []int) {
	return file_version_updater_proto_history_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRecord) GetTimeUnix() int64 {
	if x != nil && x.TimeUnix != nil {
		return *x.TimeUnix
	}
	return 0
}

func (x *UpdateRecord) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *UpdateRecord) GetLatestVersion() string {
	if x != nil && x.LatestVersion != nil {
		return *x.LatestVersion
	}
	return ""
}

func (x *UpdateRecord) GetNewReleaseFound() bool {
	if x != nil && x.NewReleaseFound != nil {
		return *x.NewReleaseFound
	}
	return false
}

func (x *UpdateRecord) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_version_updater_proto_history_proto protoreflect.FileDescriptor

const file_version_updater_proto_history_proto_rawDesc = "" +
	"\n" +
	"#version/updater/proto/history.proto\x12\rmieru.updater\"F\n" +
	"\rUpdateHistory\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.mieru.updater.UpdateRecordR\arecords\"\x8c\x02\n" +
	"\fUpdateRecord\x12\x1f\n" +
	"\btimeUnix\x18\x01 \x01(\x03H\x00R\btimeUnix\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x01R\aversion\x88\x01\x01\x12)\n" +
	"\rlatestVersion\x18\x03 \x01(\tH\x02R\rlatestVersion\x88\x01\x01\x12-\n" +
	"\x0fnewReleaseFound\x18\x04 \x01(\bH\x03R\x0fnewReleaseFound\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x04R\x05error\x88\x01\x01B\v\n" +
	"\t_timeUnixB\n" +
	"\n" +
	"\b_versionB\x10\n" +
	"\x0e_latestVersionB\x12\n" +
	"\x10_newReleaseFoundB\b\n" +
	"\x06_errorB:Z8github.com/enfein/mieru/v3/pkg/version/updater/updaterpbb\x06proto3"

var (
	file_version_updater_proto_history_proto_rawDescOnce sync.Once
	file_version_updater_proto_history_proto_rawDescData []byte
)

func file_version_updater_proto_history_proto_rawDescGZIP() []byte {
	file_version_updater_proto_history_proto_rawDescOnce.Do(func() {
		file_version_updater_proto_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_updater_proto_history_proto_rawDesc), len(file_version_updater_proto_history_proto_rawDesc)))
	})
	return file_version_updater_proto_history_proto_rawDescData
}

var file_version_updater_proto_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_version_updater_proto_history_proto_goTypes = []any{
	(*UpdateHistory)(nil), // 0: mieru.updater.UpdateHistory
	(*UpdateRecord)(nil),  // 1: mieru.updater.UpdateRecord
}
var file_version_updater_proto_history_proto_depIdxs = []int32{
	1, // 0: mieru.updater.UpdateHistory.records:type_name -> mieru.updater.UpdateRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_version_updater_proto_history_proto_init() }
func file_version_updater_proto_history_proto_init() {
	if File_version_updater_proto_history_proto != nil {
		return
	}
	file_version_updater_proto_history_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_updater_proto_history_proto_rawDesc), len(file_version_updater_proto_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_version_updater_proto_history_proto_goTypes,
		DependencyIndexes: file_version_updater_proto_history_proto_depIdxs,
		MessageInfos:      file_version_updater_proto_history_proto_msgTypes,
	}.Build()
	File_version_updater_proto_history_proto = out.File
	file_version_updater_proto_history_proto_goTypes = nil
	file_version_updater_proto_history_proto_depIdxs = nil
}
