FROM golang:1.20-alpine AS builder
RUN apk update && apk add --no-cache git
RUN git clone https://github.com/enfein/mieru.git /build
WORKDIR /build
RUN GOOS=linux CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o mita cmd/mita/mita.go

FROM alpine AS base
COPY --from=builder /build/mita /usr/local/bin/
WORKDIR /app
COPY . .
RUN chmod +x ./start.sh && adduser -H -D -g "" mita && \
    mkdir -p /etc/mita && \
    chown -R mita:mita /etc/mita && \
    chmod 775 /etc/mita && \
    mkdir -p /var/lib/mita && \
    chown -R mita:mita /var/lib/mita && \
    chmod 775 /var/lib/mita && \
    mkdir -p /var/run/mita && \
    chown -R mita:mita /var/run/mita && \
    chmod 775 /var/run/mita
CMD ["./start.sh"]
